# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4780f5fbc3ac3986b0274a2ca9c6bcafc66c5a419cd8a8b72278faf9af71a4e1131dc651a9db575fe2006f769d541347b717fccd8451824cc73e391c6d669be7

test:
  secret_key_base: 253da01b8728a4d4461cd933ef24cc54c112c747e6897d29964f87bb68c6d167b0686dff152463d9d6016f2e9a8c7675c90efd711acb943f3fa34b5f3b73cbb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
